root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main roms/games/Tetris.gb"
cmd = "go build -o ./tmp/main ."
exclude_dir = ["tmp", "etc", "fonts", "roms"]
include_ext = ["yaml", "go"]

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
clear_on_run = true
